import React from 'react';
import { Link } from 'react-router-dom';
const Home = () => {
  return <div className='dhiwise-navigation'>
      <h1>Homepage</h1>
      <p className='headline'>
        This project was generated By <a href='https://www.dhiwise.com'>Dhiwise</a>. Quickly use below links to navigate through all pages.
      </p><ul><li><Link to="/">Home1</Link></li><li><Link to="/aboutus">Aboutus</Link></li><li><Link to="/services">Services</Link></li><li><Link to="/doctors">Doctors</Link></li><li><Link to="/contact">Contact</Link></li><li><Link to="/appointment">Appointment</Link></li><li><Link to="/news">News</Link></li><li><Link to="/singlenews">SingleNews</Link></li><li><Link to="/components">Components</Link></li><li><Link to="/singleservice">SingleService</Link></li></ul>
    </div>;
};
export default Home;